<a href="https://colab.research.google.com/github/Jothini-Venkidusamy/Jothini-Codebooster-2026/blob/main/Day7/HandsOn_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install chromadb sentence-transformers -q
print("Installation complete!")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.3/23.3 MB 40.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.2/278.2 kB 10.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 50.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 37.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.8/71.8 kB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.9/170.9 kB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.3/61.3 kB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.7/203.7 kB 11.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.6/71.6 kB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 2.1 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the so

In [2]:
import pandas as pd
import numpy as np

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import chromadb

print("All libraries imported successfully!")
print(f"ChromaDB version: {chromadb.__version__}")

All libraries imported successfully!
ChromaDB version: 1.5.9


In [3]:
documents=[
    "ETL is used to clean and transform data",
    "A vehicle is a mode of transportation",
    "Cars and trucks are popular automobiles",
    "SQL is used to query databases",
    "Machine learning trains models on data"
]
query_keyword="vehicle"

print("*" *60)
print(f"KEYWORD SEARCH for:'{query_keyword}'")
print("*" *60)

for i,doc in enumerate(documents):
  if query_keyword.lower() in doc.lower():
    print(f"FOUND  [doc_{i}]: {doc}")
  else:
    print(f"MISSED [doc_{i}]:{doc}")

print()
print("PROBLEM: doc_2 talks about 'Cars and trucks' - which ARE vehicles")
print("But keyword search MISSED it because it searched for the exact word 'vehicle'")

************************************************************
KEYWORD SEARCH for:'vehicle'
************************************************************
MISSED [doc_0]:ETL is used to clean and transform data
FOUND  [doc_1]: A vehicle is a mode of transportation
MISSED [doc_2]:Cars and trucks are popular automobiles
MISSED [doc_3]:SQL is used to query databases
MISSED [doc_4]:Machine learning trains models on data

PROBLEM: doc_2 talks about 'Cars and trucks' - which ARE vehicles
But keyword search MISSED it because it searched for the exact word 'vehicle'


In [4]:
print("Loading embedding model... (maytake 1-2 minutes on first run)")
model=SentenceTransformer("all-MiniLM-L6-v2")
print("model loaded successfully!")

print(f"Model products vectors of size:{model.get_sentence_embedding_dimension()}dimensions")

Loading embedding model... (maytake 1-2 minutes on first run)


/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  | 
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

model loaded successfully!
Model products vectors of size:384dimensions


/tmp/ipykernel_751/2181401961.py:5: FutureWarning: The `get_sentence_embedding_dimension` method has been renamed to `get_embedding_dimension`.
  print(f"Model products vectors of size:{model.get_sentence_embedding_dimension()}dimensions")


In [5]:
sentence = "ETL is used to clean and transform data"

embedding = model.encode(sentence)

print(f"Input sentence: '{sentence}'")
print()

print(f"Embedding type: {type(embedding)}")
print(f"Embedding shape: {embedding.shape}")
print(f"First 10 numbers: {embedding[:10].round(4)}")

print(f"Min value: {embedding.min():.4f}")
print(f"Max value: {embedding.max():.4f}")

Input sentence: 'ETL is used to clean and transform data'

Embedding type: <class 'numpy.ndarray'>
Embedding shape: (384,)
First 10 numbers: [-0.0784  0.0541  0.0224 -0.0389  0.0221 -0.0904  0.0007 -0.0152  0.0733
  0.0362]
Min value: -0.1381
Max value: 0.1815


In [6]:
sentence =["ETL is used to clean and transform data",
           "A vehicle is a mode of transportation",
           "Cars and trucks are popular automobiles",
           "SQL is used to query databases",
           "Machine learning trains models on data"]

embedding = model.encode(sentence)

print(f"Input sentence: '{sentence}'")
print()

print(f"Embedding type: {type(embedding)}")
print(f"Embedding shape: {embedding.shape}")
print(f"First 10 numbers: {embedding[:10].round(4)}")

print(f"Min value: {embedding.min():.4f}")
print(f"Max value: {embedding.max():.4f}")

Input sentence: '['ETL is used to clean and transform data', 'A vehicle is a mode of transportation', 'Cars and trucks are popular automobiles', 'SQL is used to query databases', 'Machine learning trains models on data']'

Embedding type: <class 'numpy.ndarray'>
Embedding shape: (5, 384)
First 10 numbers: [[-0.0784  0.0541  0.0224 ...  0.0011  0.0316  0.0009]
 [-0.005  -0.0067  0.0068 ...  0.0669  0.0594 -0.0416]
 [ 0.0925 -0.0383  0.0287 ...  0.0212  0.092   0.0369]
 [ 0.0298 -0.0137 -0.0951 ...  0.0411  0.0983 -0.0323]
 [-0.0604 -0.1063  0.0693 ... -0.0024 -0.0141 -0.041 ]]
Min value: -0.2101
Max value: 0.1815


In [7]:

documents = [
    "ETL is used to clean and transform data",
    "A vehicle is a mode of transportation",
    "Cars and trucks are popular automobiles",
    "SQL is used to query databases",
    "Machine learning trains models on data"
]

query = "vehicle"

print("*" * 60)
print(f"SEMANTIC SEARCH for: '{query}'")
print("*" * 60)


query_embedding = model.encode(query)
doc_embeddings = model.encode(documents)

for i, doc_embedding in enumerate(doc_embeddings):
    similarity = cosine_similarity(
        [query_embedding],
        [doc_embedding]
    )[0][0]


    if similarity > 0.3:
        print(f"FOUND  [doc_{i}]: {documents[i]}")
    else:
        print(f"MISSED [doc_{i}]: {documents[i]}")

print()
print("Semantic search understands meaning.")
print("Cars and trucks are vehicles, so doc_2 is FOUND.")

************************************************************
SEMANTIC SEARCH for: 'vehicle'
************************************************************
MISSED [doc_0]: ETL is used to clean and transform data
FOUND  [doc_1]: A vehicle is a mode of transportation
FOUND  [doc_2]: Cars and trucks are popular automobiles
MISSED [doc_3]: SQL is used to query databases
MISSED [doc_4]: Machine learning trains models on data

Semantic search understands meaning.
Cars and trucks are vehicles, so doc_2 is FOUND.


In [8]:
sentence =[
    "ETL is used to clean and transform data",
    "A vehicle is a mode of transportation",
    "Cars and trucks are popular automobiles"
]

embedding = model.encode(sentence)

print(f"Number of sentence : {len(sentence)}")
print(f"Shape of Embedding array: {embedding.shape}")
print()

print("Each row is one sentence's embedding:")
for i,sent in enumerate(sentence):
  print(f" Sentence {i} : shape={embedding[i].shape},first 5 values={embedding[i][:5].round(3)}")



Number of sentence : 3
Shape of Embedding array: (3, 384)

Each row is one sentence's embedding:
 Sentence 0 : shape=(384,),first 5 values=[-0.078  0.054  0.022 -0.039  0.022]
 Sentence 1 : shape=(384,),first 5 values=[-0.005 -0.007  0.007  0.041 -0.007]
 Sentence 2 : shape=(384,),first 5 values=[ 0.092 -0.038  0.029  0.031  0.009]


In [9]:
your_sentences = [
    "I enjoy watching web series in my free time.",
    "The web series has an interesting story and great characters.",
    "Many people prefer web series because they can watch episodes anytime."
]

your_embeddings = model.encode(your_sentences)

sim_your_01 = cosine_similarity(
    [your_embeddings[0]],
    [your_embeddings[1]]
)[0][0]

sim_your_02 = cosine_similarity(
    [your_embeddings[0]],
    [your_embeddings[2]]
)[0][0]

print("Final Sentences: ")
print("*" * 60)

print(f"Sentence A: '{your_sentences[0]}'")
print(f"Sentence B: '{your_sentences[1]}'")
print(f"Sentence C: '{your_sentences[2]}'")
print()

print(f"Similarity (A vs B): {sim_your_01:.4f}")
print(f"Similarity (A vs C): {sim_your_02:.4f}")
print()

Final Sentences: 
************************************************************
Sentence A: 'I enjoy watching web series in my free time.'
Sentence B: 'The web series has an interesting story and great characters.'
Sentence C: 'Many people prefer web series because they can watch episodes anytime.'

Similarity (A vs B): 0.5965
Similarity (A vs C): 0.7414



In [10]:
chroma_client =chromadb.Client()
collection=chroma_client.get_or_create_collection("demo_notes")
print("ChromaDB client created (in-memory mode)")


print(f"Collection name:demo_notes ")
print(f"Documents in collection :{collection.count()}")

ChromaDB client created (in-memory mode)
Collection name:demo_notes 
Documents in collection :0


In [11]:
sample_docs = [
    "ETL is used to clean and transform data",
    "A vehicle is a mode of transportation",
    "Cars and trucks are popular automobiles",
    "SQL is used to query databases",
    "Machine learning trains models on data"
]

sample_ids=["doc_1","doc_2","doc_3","doc_4","doc_5"]
sample_metadata=[
    {"subject":"Data Engineering","topic":"ETL"},
    {"subject":"Data Engineering","topic":"SQL"},
    {"subject":"ML","topic":"ML Basic"},
    {"subject":"Python","topic":"Pandas"},
    {"subject":"ML","topic":"Neural Networks"}
]
collection.add(
    documents=sample_docs,
    ids=sample_ids,
    metadatas=sample_metadata
)
print(f"Documents added to collection!")
print(f"Total documents now in collection:{collection.count()}")

/root/.cache/chroma/onnx_models/all-MiniLM-L6-v2/onnx.tar.gz: 100%|██████████| 79.3M/79.3M [00:01<00:00, 48.8MiB/s]


Documents added to collection!
Total documents now in collection:5


In [12]:
query="How do I clean prepare data?"
results=collection.query(
    query_texts=[query],
    n_results=3
)
print("RESULTS KEYS AVAILABLE:")
print(list(results.keys()))

RESULTS KEYS AVAILABLE:
['ids', 'embeddings', 'documents', 'uris', 'included', 'data', 'metadatas', 'distances']


In [13]:
print(f"Query:'{query}'")
print("*" * 60)
print()

matched_docs=results['documents'][0]
matched_ids=results['ids'][0]
matched_distances=results['distances'][0]
matched_metadatas=results['metadatas'][0]

for rank, (doc,doc_id,dist,meta) in enumerate(zip(matched_docs,matched_ids,matched_distances,matched_metadatas)):
   print(f"RANK {rank} | ID: {doc_id} | Distance: {dist:.4f}")
   print(f"Subject: {meta['subject']} | Topic: {meta['topic']}")
   print(f"Document: {doc}")
   print()

print("NOTICE: The Results are about ETL and pandas-exaclty what 'clean and perpare data")
print("Semantic search found them even through the words are different")

Query:'How do I clean prepare data?'
************************************************************

RANK 0 | ID: doc_1 | Distance: 1.2422
Subject: Data Engineering | Topic: ETL
Document: ETL is used to clean and transform data

RANK 1 | ID: doc_4 | Distance: 1.5608
Subject: Python | Topic: Pandas
Document: SQL is used to query databases

RANK 2 | ID: doc_5 | Distance: 1.8165
Subject: ML | Topic: Neural Networks
Document: Machine learning trains models on data

NOTICE: The Results are about ETL and pandas-exaclty what 'clean and perpare data
Semantic search found them even through the words are different


In [14]:
filtered_results = collection.query(
    query_texts=[query],
    n_results=3,
    where={"subject": "Data Engineering"}
)
print(f"FILTERED QUERY: {query}")
print("Filter only Machine Learning documents")
print("="*60)

for rank, (doc, dist, meta) in enumerate(zip(
    filtered_results['documents'][0],
    filtered_results['distances'][0],
    filtered_results['metadatas'][0]),start=1):
  print(f"Rank: {rank} | Distance: {dist:.2f} | Subject: {meta['subject']}")
  print(f"{doc}\n")

FILTERED QUERY: How do I clean prepare data?
Filter only Machine Learning documents
Rank: 1 | Distance: 1.24 | Subject: Data Engineering
ETL is used to clean and transform data

Rank: 2 | Distance: 2.19 | Subject: Data Engineering
A vehicle is a mode of transportation



In [17]:
print("DISTANCE TO SIMILARITY CONVERSION")
print(f"{'Distance':<15}{'Similarity':<15}{'Interpretation':<20}")
distances=[0.05,0.20,0.40,0.65,0.90]
interpretations=["Near identical","Very similar","Related","Somewhat related","Not related"]
for dist,interp in zip(distances,interpretations):
  similarity=1-dist
  print(f"{dist:<15.2f}{similarity:<15.2f}{interp:<20}")

DISTANCE TO SIMILARITY CONVERSION
Distance       Similarity     Interpretation      
0.05           0.95           Near identical      
0.20           0.80           Very similar        
0.40           0.60           Related             
0.65           0.35           Somewhat related    
0.90           0.10           Not related         
